name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install apt packages
      run: sudo apt-get install libavahi-compat-libdnssd-dev jq
  
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
          
    - uses: actions/checkout@v2
      
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

        
    - uses: EndBug/version-check@v1.2.0
      name: Check for version change
      id: check_version
      with:
        diff-search: true

    - name: Build addon package
      #if: steps.check_version.outputs.changed == 'true'
      run: ./build.sh
      
    - uses: actions/upload-artifact@v1
      name: Save release artifacts
      #if: steps.check_version.outputs.changed == 'true'
      with:
        name: release
        path: dist

    - uses: actions/upload-artifact@v1
      name: Save changelog
      #if: steps.check_version.outputs.changed == 'true'
      with:
        name: description
        path: RELEASE_BODY.md
 
